env:
  CIRRUS_CLONE_SUBMODULES: 'true'
  RUST_BACKTRACE: '1'

build_and_test: &BUILD_AND_TEST
  setup_script:
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y --default-toolchain stable
  test_script:
    - cargo test

freebsd_task:
  name: Test (x86_64 FreeBSD)
  freebsd_instance:
    image_family: freebsd-13-1
  env:
    PATH: $HOME/.cargo/bin:$PATH
  registry_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.toml
  target_cache:
    folder: target
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.toml
  install_script:
    - pkg install -y curl bash
  <<: *BUILD_AND_TEST

macos_arm64_task:
  name: Test (arm64 macOS)
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  env:
    PATH: $HOME/.cargo/bin:$PATH
  registry_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.toml
  target_cache:
    folder: target
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.toml
  <<: *BUILD_AND_TEST

linux_aarch64_task:
  name: Test (arm64 Linux)
  arm_container:
    image: ubuntu:22.04
    cpu: 4
    memory: 4G
  env:
    PATH: $HOME/.cargo/bin:$PATH
  registry_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.toml
  target_cache:
    folder: target
    fingerprint_script:
      - echo $CIRRUS_OS
      - cat Cargo.toml
  install_script:
    - apt-get update && apt-get install -y curl build-essential
  <<: *BUILD_AND_TEST