sudo: required
dist: trusty
language: rust
addons:
  apt:
    packages:
      - libssl-dev
rust:
  - stable
  - nightly

cache: cargo

script:
  - cargo test

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo install cargo-tarpaulin --git https://github.com/xd009642/tarpaulin --branch develop
      cargo tarpaulin --no-count --exclude-files *.h *.c* --out Xml
      bash <(curl -s https://codecov.io/bash)
    fi
